### ISSUE TITLE
Define Step Function

### ISSUE THREAD

**Issue by mike-audi** [tiki/core-account-subscription-estimate#4]
### Reason

Create a step function to execute the requests required for subscription estimation

### Description

The step function requires the following request parameters
- query
- requestId

The step function should then execute the following tasks

1) Wrap the query in a count statement: `SELECT COUNT(*) as "total" FROM ( query );`
2) Execute the count query using the Athena StartQueryExecution Step
3) Wrap the query in a sample statement: `SELECT * FROM ( query ) LIMIT 3;`
4) Execute the sample statement using the Athena StartQueryExecution Step
5) Using the Call third-party API step, with a body containing the requestId and the locations of the results (look for field OutputLocation)

- For auth of the Call third-party API step use the existing registered core-account-sf endpoint
- Use callback path of `POST https://account.mytiki.com/api/latest/ocean?event=subscription-estimate`

### Success Criteria

- [ ] Defined input and output json to the step function
- [ ] Step function executes count query
- [ ] Step function executes sample query
- [ ] Step function calls back to account service with the results

**Comment by ricardobrg** [comment]
@MiroBenicio is waiting on AWS permissions
